### ISSUE TITLE
Add search feature

### ISSUE THREAD

**Issue by globalistas** [peltho/tufw#3]
First of all, happy to have found this. I'm adding new bot-blocking rules (by IP) on my server daily and it's becoming more difficult to keep track and edit/delete the ufw rules just in the cli.

Would it be possible to add a search function, so you can e.g. search for an IP to see if it's been already added in a rule?

Thanks!

**Comment by peltho** [comment]
Thanks for your feedback @globalistas !
Happy to share tufw as well

I will think about the search feature during my spare time.
Feel free to provide any other feedback 🙏

**Comment by peltho** [comment]
I just added such a feature. 
Feel free to open another issue / PR to contribute :pray:
