### ISSUE TITLE
how to make transparent background  ?

### ISSUE THREAD

**Issue by sachinsenal0x64** [peltho/tufw#7]
os = arch

wm = qtile

**Comment by peltho** [comment]
What terminal do you use?
I think it's rather a terminal configuration matter than a software issue

**Comment by sachinsenal0x64** [comment]
> What terminal do you use? I think it's rather a terminal configuration issue than a software one.

![image](https://github.com/peltho/tufw/assets/127573781/541eae1e-95bc-4772-9361-b058101616e6)

Wezterm

**Comment by peltho** [comment]
https://wezfurlong.org/wezterm/config/appearance.html#window-background-gradient

I think you can find whatever you need in the corresponding documentation.
Closing this issue because it's unrelated with tufw.
